[
    {
        "Author": "Emz Lyne",
        "Name": "Mahjong Reader",
        "Punchline": "Cant count? This is for you",
        "Description": "Just opens when you start match",
        "Changelog": "",
        "InternalName": "Mahjong reader",
        "AssemblyVersion": "1.0",
        "RepoUrl": "https://github.com/Kittemzly/FFXIVMahjongReader",
        "ApplicableVersion": "any",
        "CategoryTags": [
            "utility"
        ],
        "DalamudApiLevel": 12,
        "IconUrl": "https://i.imgur.com/jTo1na1.png",
        "ImageUrls": [
            ""
        ],
        "DownloadLinkInstall": "hhttps://github.com/Kittemzly/FFXIVMahjongReader/blob/master/src/MahjongReader/bin/Release/MahjongReader/latest.zip",
        "IsHide": false,
        "IsTestingExclusive": false,
        "DownloadLinkTesting": "https://github.com/Kittemzly/FFXIVMahjongReader/blob/master/src/MahjongReader/bin/Release/MahjongReader/latest.zip",
        "DownloadLinkUpdate": "https://github.com/Kittemzly/FFXIVMahjongReader/blob/master/src/MahjongReader/bin/Release/MahjongReader/latest.zip",
        "DownloadCount": 0,
        "LastUpdate": ""
    }
]
